import { Platform, StyleSheet } from 'react-native';
import {
  SPACING,
  RADIUS,
  SCREEN_PADDING,
  COLORS,
  TREASY_TYPE_SCALE,
  TREASY_DARK_TEXT,
} from '../shared/theme/tokens';
import {
  HOME_SCREEN_STYLE_COLORS,
  HOME_SCREEN_STYLE_RGBA,
  HOME_SCREEN_STYLE_SHADOWS,
} from './HomeScreen/HomeScreen.styleTokens';

const LAST_WORKOUT_CHIP_BORDER_WIDTH = 1;
const LAST_WORKOUT_CHIP_MAX_ROWS = 2;
const LAST_WORKOUT_CHIP_ROW_HEIGHT =
  TREASY_TYPE_SCALE.t3.lineHeight + SPACING.xs * 2 + LAST_WORKOUT_CHIP_BORDER_WIDTH * 2;
const LAST_WORKOUT_CHIP_MAX_HEIGHT =
  LAST_WORKOUT_CHIP_ROW_HEIGHT * LAST_WORKOUT_CHIP_MAX_ROWS + SPACING.xs * (LAST_WORKOUT_CHIP_MAX_ROWS - 1);
const PREVIOUS_WORKOUT_EXAMPLE_DETAIL_ROW_MIN_HEIGHT = TREASY_TYPE_SCALE.t5.lineHeight - 1;
const PREVIOUS_WORKOUT_HOME_CARD_MIN_HEIGHT = Math.ceil(
  SPACING.xl * 2 +
    TREASY_TYPE_SCALE.t3.lineHeight +
    (TREASY_TYPE_SCALE.t2.lineHeight + SPACING.xs) +
    LAST_WORKOUT_CHIP_MAX_HEIGHT +
    (TREASY_TYPE_SCALE.t5.lineHeight + 2 + (TREASY_TYPE_SCALE.t0.lineHeight - 2) + SPACING.xs) +
    StyleSheet.hairlineWidth +
    ((TREASY_TYPE_SCALE.t4.lineHeight - 2) + (TREASY_TYPE_SCALE.t6.lineHeight - 2) + 2 + SPACING.xs) +
    TREASY_TYPE_SCALE.t6.lineHeight +
    SPACING.md * 6
);

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.treasyNavy,
    ...Platform.select({
      web: { width: '100%', maxWidth: 720, alignSelf: 'center' },
    }),
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SCREEN_PADDING,
    paddingTop: 0,
  },
  stickyWordmarkWrap: {
    position: 'absolute',
    left: SCREEN_PADDING,
    zIndex: 25,
    ...Platform.select({
      android: { elevation: 5 },
    }),
  },
  wordmarkButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingRight: SPACING.sm,
    alignSelf: 'stretch',
    flexShrink: 1,
    transform: [{ translateY: 4 }],
  },
  stickyWordmarkButton: {
    alignSelf: 'flex-start',
    paddingRight: 0,
  },
  wordmarkPressed: {
    opacity: 0.72,
  },
  wordmarkText: {
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    letterSpacing: -0.2,
    fontWeight: '600',
  },
  wordmarkTextMain: {
    color: COLORS.blue1,
    ...Platform.select({ web: { fontWeight: '600' } }),
  },
  wordmarkDot: {
    color: HOME_SCREEN_STYLE_COLORS.wordmarkDot,
    ...Platform.select({ web: { fontWeight: '600' } }),
  },
  wordmarkDotGlow: {
    textShadowColor: HOME_SCREEN_STYLE_RGBA.wordmarkDotGlow,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerWordmarkSpacer: {
    minHeight: 44,
    width: 136,
  },
  compassSheetBackdrop: {
    flex: 1,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.backdropScrim,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.lg,
  },
  compassSheetCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.compassNavy,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.compassBorder,
    paddingBottom: SPACING.xs,
    overflow: 'hidden',
    shadowColor: HOME_SCREEN_STYLE_COLORS.black,
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  compassSheetHeader: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: HOME_SCREEN_STYLE_COLORS.compassBorder,
  },
  compassSheetTitle: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  compassAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
  },
  compassActionDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: HOME_SCREEN_STYLE_COLORS.compassBorder,
  },
  compassActionPressed: {
    backgroundColor: HOME_SCREEN_STYLE_RGBA.actionPressBlue,
  },
  compassActionText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  compassActionChevron: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '700',
  },
  headerActions: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  settingsButton: {
    minWidth: 44,
    minHeight: 44,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsIcon: {
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
  },
  sectionTitle: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '600',
    marginBottom: SPACING.sm,
  },
  section: {
    gap: SPACING.md,
    marginBottom: SPACING.xxl,
  },
  quickLogCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: RADIUS.lg,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.sm,
    paddingHorizontal: SPACING.md,
    flexDirection: 'column',
    alignItems: 'stretch',
    borderWidth: 1,
    marginBottom: SPACING.xl,
    ...Platform.select({
      web: { minHeight: 120 },
    }),
  },
  quickLogTopSection: {
    flexGrow: 1,
    gap: SPACING.xs,
  },
  quickLogTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.md,
    marginTop: 0,
    marginBottom: SPACING.xs,
  },
  quickLogTitleCluster: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    alignSelf: 'flex-start',
  },
  quickLogMomentum: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginTop: SPACING.sm,
    marginBottom: 4,
    width: '100%',
  },
  quickLogMomentumMain: {
    color: HOME_SCREEN_STYLE_COLORS.success,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '600',
  },
  quickLogMomentumSub: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
  },
  quickLogMomentumLink: {
    color: HOME_SCREEN_STYLE_COLORS.bluePrimary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    marginTop: 6,
    textDecorationLine: 'underline',
  },
  quickLogTitle: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.14,
    textShadowColor: HOME_SCREEN_STYLE_COLORS.transparent,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
    marginBottom: 0,
  },
  quickLogEmoji: {
    alignSelf: 'flex-start',
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    color: HOME_SCREEN_STYLE_COLORS.textBright,
  },
  quickLogSubtitle: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    marginBottom: SPACING.xs,
  },
  quickLogExampleRow: {
    marginTop: SPACING.xs,
    minHeight: 24,
  },
  quickLogExampleText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '600',
  },
  blockButton: {
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    justifyContent: 'center',
    borderWidth: 1,
    minHeight: 52,
  },
  blockLabel: {
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  groupsWrapper: {
    marginBottom: SPACING.sm,
  },
  twoColumnRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: SPACING.lg,
    rowGap: SPACING.lg,
    width: '100%',
  },
  twoColumnRowStretch: {
    alignItems: 'stretch',
  },
  twoColumnRowSectionGap: {
    marginTop: SPACING.xs,
  },
  lowerSection: {
    width: '100%',
  },
  lowerRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    columnGap: SPACING.lg,
    width: '100%',
    height: '100%',
  },
  leftCol: {
    flex: 1,
    height: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    minWidth: 0,
  },
  rightCol: {
    flex: 1,
    height: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    minWidth: 0,
  },
  notertFill: {
    flex: 1,
    alignSelf: 'stretch',
  },
  notertMeasure: {
    alignSelf: 'stretch',
  },
  lowerGap: {
    height: SPACING.sm,
  },
  lastWorkoutToNotesGap: {
    height: SPACING.md,
  },
  groupsColumn: {
    gap: SPACING.md,
  },
  leftColumn: {
    flex: 1,
    minWidth: 0,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  sideColumn: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  rightColumn: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'stretch',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  groupsTitle: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '600',
    marginBottom: SPACING.sm,
  },
  groupsList: {
    gap: SPACING.md,
  },
  groupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.blueWash,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDarkBorder,
    paddingVertical: SPACING.sm + 1,
    paddingHorizontal: SPACING.md,
    minHeight: 54,
    width: '100%',
    alignSelf: 'stretch',
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: '0 8px 18px rgba(2, 6, 23, 0.2)' },
      default: {
        shadowColor: HOME_SCREEN_STYLE_COLORS.black,
        shadowOpacity: 0.16,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
      },
    }),
  },
  groupIconWrap: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    borderWidth: 1,
  },
  groupIconStack: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupIcon: {
    width: 24,
    height: 24,
  },
  groupIconOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  groupDotSmall: {
    width: 8,
    height: 8,
    borderRadius: 999,
    opacity: 0.85,
  },
  groupDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  groupRowText: {
    flex: 1,
    color: COLORS.blue1,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '700',
    marginHorizontal: SPACING.xs,
    minWidth: 0,
  },
  groupRowTextTight: {
    marginHorizontal: 2,
  },
  groupAction: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_RGBA.actionPressBlue,
    marginRight: SPACING.sm,
  },
  groupActionText: {
    color: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  analysisNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDark,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDarkBorder,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    minHeight: 48,
    width: '100%',
  },
  largeNavTile: {
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
  },
  statusNavTile: {
    height: 100,
    paddingVertical: SPACING.lg,
  },
  notertTallTile: {
    height: 112,
    alignSelf: 'stretch',
  },
  notertCardSurface: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMuted,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMutedBorder,
    overflow: 'hidden',
  },
  analysisTallTile: {
    minHeight: 100,
  },
  analysisCardSurface: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMuted,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMutedBorder,
    position: 'relative',
    overflow: 'hidden',
  },
  analysisCardAccentTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.progressFillMuted,
  },
  analysisCardAccentStripe: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.neutralStrong,
  },
  analysisCardForeground: {
    position: 'relative',
    zIndex: 1,
  },
  todayWorkoutTile: {
    minHeight: 100,
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  todayWorkoutCardSurface: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMuted,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMutedBorder,
  },
  todayWorkoutAccentTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.progressFillIdle,
  },
  todayWorkoutAccentStripe: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.neutralStrong,
  },
  todayWorkoutForeground: {
    position: 'relative',
    zIndex: 1,
  },
  todayWorkoutTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 22,
    gap: SPACING.sm,
  },
  todayWorkoutTitleText: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
    flexShrink: 1,
  },
  todayLiveBadge: {
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    width: 64,
    minHeight: 24,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todayLiveBadgeActive: {
    borderColor: HOME_SCREEN_STYLE_COLORS.success,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.liveSuccessSoft,
  },
  todayLiveBadgeIdle: {
    borderColor: HOME_SCREEN_STYLE_COLORS.neutralStrong,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.progressFillMuted,
  },
  todayLiveBadgeText: {
    color: HOME_SCREEN_STYLE_COLORS.success,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  analysisAlignWrap: {
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    width: '100%',
  },
  analysisAlignStretch: {
    flexGrow: 1,
    alignSelf: 'stretch',
  },
  analysisNavText: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  analysisCardTitleText: {
    color: HOME_SCREEN_STYLE_COLORS.bluePrimary,
  },
  navTileTitleCompact: {
    color: HOME_SCREEN_STYLE_COLORS.blueSubtle,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  largeNavText: {
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
  },
  navTileTitleSoft: {
    color: HOME_SCREEN_STYLE_COLORS.blueSubtle,
    fontWeight: '600',
  },
  navTileLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    minWidth: 0,
  },
  notertTileLeft: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: SPACING.xs,
    justifyContent: 'center',
  },
  notertHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.sm,
  },
  notesHeaderAffordance: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: SPACING.xs,
    marginLeft: SPACING.xs,
    flexShrink: 0,
  },
  notesHeaderChevron: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  notertHeaderText: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.2,
    flex: 1,
  },
  notertCountChip: {
    minWidth: 24,
    minHeight: 20,
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.xs,
  },
  notertCountText: {
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  notertContentDivider: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
  },
  notertPreviewList: {
    gap: SPACING.xs,
  },
  notertLineText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  notertEmptyText: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
  },
  notertOverflowText: {
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    textAlign: 'right',
  },
  notePreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    width: '100%',
    minHeight: TREASY_TYPE_SCALE.t6.lineHeight,
  },
  notePreviewDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.linkSoft,
    opacity: 0.85,
    flexShrink: 0,
  },
  notePreviewDotPlaceholder: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.transparent,
  },
  notePreviewText: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  notePreviewPlaceholder: {
    color: HOME_SCREEN_STYLE_COLORS.transparent,
  },
  navTileIconWrap: {
    width: 30,
    height: 30,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    marginTop: 1,
  },
  navTileIconWrapNote: {
    backgroundColor: HOME_SCREEN_STYLE_RGBA.cardIconBlueBg,
    borderColor: HOME_SCREEN_STYLE_RGBA.cardIconBlueBorder,
  },
  navTileIconWrapAnalysis: {
    backgroundColor: HOME_SCREEN_STYLE_RGBA.cardIconGreenBg,
    borderColor: HOME_SCREEN_STYLE_RGBA.cardIconGreenBorder,
  },
  todayWorkoutIconWrap: {
    backgroundColor: HOME_SCREEN_STYLE_RGBA.cardIconSkyBg,
    borderColor: HOME_SCREEN_STYLE_RGBA.cardIconSkyBorder,
  },
  navTileIconText: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '700',
  },
  navTileTextStack: {
    flex: 1,
    justifyContent: 'flex-start',
    minWidth: 0,
  },
  navTileSubText: {
    marginTop: 6,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  navTileMetricValue: {
    marginTop: 4,
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    fontWeight: '700',
  },
  analysisCardMetricValue: {
    color: HOME_SCREEN_STYLE_COLORS.success,
  },
  navTileMetricContext: {
    marginTop: 3,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
  },
  analysisCardMetricContext: {
    color: HOME_SCREEN_STYLE_COLORS.neutral,
  },
  todayWorkoutMetricValue: {
    marginTop: 4,
    color: HOME_SCREEN_STYLE_COLORS.bluePrimary,
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
  },
  todayWorkoutMetricValueCompleted: {
    color: HOME_SCREEN_STYLE_COLORS.textEmphasis,
    fontWeight: '700',
    letterSpacing: 0.18,
    textShadowColor: HOME_SCREEN_STYLE_RGBA.titleShadowDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  todayWorkoutMetricValueCompletedLight: {
    color: HOME_SCREEN_STYLE_COLORS.slateMuted,
    textShadowColor: HOME_SCREEN_STYLE_RGBA.titleShadowLight,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  todayWorkoutMetricCheckmark: {
    color: HOME_SCREEN_STYLE_COLORS.success,
  },
  todayWorkoutSecondaryText: {
    marginTop: 3,
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  todayWorkoutMetaText: {
    marginTop: 6,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
    fontVariant: ['tabular-nums'],
    ...Platform.select({
      web: { fontFeatureSettings: '"tnum"' },
    }),
  },
  navTileSubLabel: {
    color: HOME_SCREEN_STYLE_COLORS.neutral,
    fontWeight: '700',
  },
  navTileSubValue: {
    color: HOME_SCREEN_STYLE_COLORS.textSoft,
    fontWeight: '700',
  },
  navTileSubEmpty: {
    color: HOME_SCREEN_STYLE_COLORS.neutral,
    fontWeight: '600',
  },
  analysisCardSubText: {
    color: HOME_SCREEN_STYLE_COLORS.neutral,
  },
  analysisNavChevron: {
    marginLeft: 'auto',
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t1.size,
    fontWeight: '600',
    lineHeight: TREASY_TYPE_SCALE.t1.lineHeight,
  },
  analysisCardChevron: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
  },
  lastWorkoutCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDark,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDarkBorder,
    minHeight: PREVIOUS_WORKOUT_HOME_CARD_MIN_HEIGHT,
    padding: SPACING.xl,
    gap: SPACING.md,
    width: '100%',
    alignItems: 'center',
    overflow: 'hidden',
  },
  lastWorkoutPressWrap: {
    width: '100%',
  },
  lastWorkoutCardHidden: {
    opacity: 0,
  },
  lastWorkoutTitle: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.12,
    marginBottom: SPACING.xs,
    textAlign: 'center',
  },
  lastWorkoutSectionLabel: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
    marginBottom: SPACING.xs,
    textAlign: 'center',
  },
  lastWorkoutChipScroll: {
    width: '100%',
  },
  lastWorkoutChips: {
    width: '100%',
    alignSelf: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
    gap: SPACING.xs,
    justifyContent: 'flex-start',
    maxHeight: LAST_WORKOUT_CHIP_MAX_HEIGHT,
    overflow: 'hidden',
  },
  previousWorkoutChipsReserved: {
    minHeight: LAST_WORKOUT_CHIP_MAX_HEIGHT,
  },
  previousWorkoutChipsFluid: {
    maxHeight: 999,
    minHeight: 0,
    justifyContent: 'flex-start',
  },
  muscleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.pill,
    borderWidth: LAST_WORKOUT_CHIP_BORDER_WIDTH,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.slateDeep,
  },
  muscleChipDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  muscleChipText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  previousWorkoutChipCompact: {
    gap: 6,
    minHeight: 24,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 2,
  },
  previousWorkoutChipTwoColumn: {
    flexBasis: '48.5%',
    maxWidth: '48.5%',
    minWidth: 0,
    flexGrow: 0,
  },
  previousWorkoutChipDotCompact: {
    width: 6,
    height: 6,
  },
  previousWorkoutChipTextCompact: {
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    flexShrink: 1,
  },
  previousWorkoutChipOverflowCompact: {
    minWidth: 30,
    justifyContent: 'center',
  },
  lastWorkoutDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    width: '100%',
  },
  lastWorkoutDate: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
    textAlign: 'center',
  },
  lastWorkoutList: {
    gap: SPACING.sm,
  },
  lastWorkoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  lastDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  lastWorkoutName: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t4.size,
    lineHeight: TREASY_TYPE_SCALE.t4.lineHeight,
    fontWeight: '600',
  },
  lastWorkoutDetail: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    marginTop: 2,
  },
  lastWorkoutTotalStack: {
    alignItems: 'center',
    marginBottom: SPACING.xs,
    gap: 2,
  },
  lastWorkoutTotalLabel: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
    textAlign: 'center',
  },
  lastWorkoutTotalValue: {
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    fontWeight: '700',
    textAlign: 'center',
  },
  previousWorkoutTotalVolumeValueCompact: {
    fontSize: TREASY_TYPE_SCALE.t0.size - 2,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight - 2,
  },
  lastWorkoutMetricNumber: {
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    fontWeight: '700',
  },
  lastWorkoutMetricUnit: {
    color: HOME_SCREEN_STYLE_COLORS.indigoDeep,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '600',
  },
  previousWorkoutTotalVolumeUnitCompact: {
    fontSize: TREASY_TYPE_SCALE.t5.size - 1,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight - 1,
  },
  lastWorkoutMetricSeparator: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
  },
  lastWorkoutExampleBlock: {
    alignItems: 'center',
    gap: 2,
    marginBottom: SPACING.xs,
  },
  lastWorkoutExampleName: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t4.size,
    lineHeight: TREASY_TYPE_SCALE.t4.lineHeight,
    fontWeight: '600',
    textAlign: 'center',
  },
  previousWorkoutExerciseNameCompact: {
    fontSize: TREASY_TYPE_SCALE.t4.size - 2,
    lineHeight: TREASY_TYPE_SCALE.t4.lineHeight - 2,
  },
  lastWorkoutExampleDetail: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
    textAlign: 'center',
  },
  previousWorkoutExerciseMetricsCompact: {
    fontSize: TREASY_TYPE_SCALE.t6.size - 2,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight - 2,
  },
  previousWorkoutExerciseMetricUnitCompact: {
    fontSize: TREASY_TYPE_SCALE.t5.size - 1,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight - 1,
  },
  previousWorkoutExerciseDetailRowReserved: {
    minHeight: PREVIOUS_WORKOUT_EXAMPLE_DETAIL_ROW_MIN_HEIGHT,
    justifyContent: 'center',
  },
  previousWorkoutExerciseDetailPlaceholder: {
    opacity: 0,
  },
  previousWorkoutExercisePreviewReserved: {
    minHeight: (TREASY_TYPE_SCALE.t4.lineHeight - 2) + (TREASY_TYPE_SCALE.t6.lineHeight - 2) + 2 + SPACING.xs,
  },
  previousWorkoutExercisePreviewHidden: {
    opacity: 0,
  },
  lastWorkoutEmpty: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
    textAlign: 'center',
  },
  lastWorkoutLink: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  lastWorkoutPreviewBackdrop: {
    flex: 1,
  },
  lastWorkoutPreviewDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.treasyNavy,
  },
  lastWorkoutPreviewCard: {
    position: 'absolute',
    zIndex: 2,
  },
  todayPanelOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  todayPanelBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  todayPanelBackdropDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.treasyNavy,
  },
  todayPanelSheet: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.panelNavy,
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeBlueDark,
    borderBottomWidth: 0,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    overflow: 'hidden',
    ...Platform.select({
      web: { boxShadow: HOME_SCREEN_STYLE_SHADOWS.todayPanelWeb },
      default: {
        shadowColor: HOME_SCREEN_STYLE_COLORS.treasyNavy,
        shadowOpacity: 0.45,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: -6 },
      },
    }),
  },
  todayPanelHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.slateMuted,
    marginBottom: SPACING.sm,
  },
  todayPanelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  todayPanelHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  todayPanelTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  todayPanelHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  todayPanelTitle: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  todayPanelDateText: {
    marginTop: 4,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  todayPanelLiveBadge: {
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todayPanelLiveBadgeText: {
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  todayPanelHeaderAccent: {
    height: 1,
    borderRadius: RADIUS.pill,
    marginBottom: SPACING.md,
  },
  todayFinishButton: {
    minHeight: 36,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_RGBA.finishBorder,
    backgroundColor: HOME_SCREEN_STYLE_RGBA.finishBg,
    paddingHorizontal: SPACING.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todayFinishButtonText: {
    color: HOME_SCREEN_STYLE_COLORS.successPale,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  todayPanelCloseButton: {
    minWidth: 36,
    minHeight: 36,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.slateMuted,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.slateDeep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todayPanelCloseText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '700',
  },
  todayPanelScroll: {
    flex: 1,
  },
  todayPanelScrollContent: {
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  todayTimerCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    position: 'relative',
    overflow: 'hidden',
  },
  todayTimerTintLayer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: RADIUS.lg,
  },
  todayTimerForeground: {
    position: 'relative',
    zIndex: 1,
  },
  todayTimerValue: {
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    fontWeight: '700',
    letterSpacing: 0.25,
  },
  todayTimerHelp: {
    marginTop: 4,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  todaySummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  todaySummaryCard: {
    flexGrow: 1,
    minWidth: 124,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  todaySummaryLabel: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
  },
  todaySummaryValue: {
    marginTop: 4,
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '700',
  },
  todaySummaryTopValue: {
    color: HOME_SCREEN_STYLE_COLORS.blueSubtle,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
  },
  todayMuscleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
  },
  todayMuscleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.slateDeep,
  },
  todayMuscleDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  todayMuscleText: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  todayTimelineList: {
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  todayExerciseRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  todayTimelineRail: {
    width: 16,
    alignItems: 'center',
    paddingTop: SPACING.sm,
  },
  todayTimelineDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.bluePrimary,
  },
  todayTimelineLine: {
    flex: 1,
    width: 1,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.strokeBlueDark,
    marginTop: 2,
    marginBottom: -2,
  },
  todayExerciseCard: {
    flex: 1,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  todayExerciseHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  todayExerciseMetaRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  todayExerciseTitle: {
    flex: 1,
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t4.size,
    lineHeight: TREASY_TYPE_SCALE.t4.lineHeight,
    fontWeight: '600',
  },
  todayExerciseTime: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  todayExerciseVolume: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  todayExerciseSetLine: {
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '400',
    marginTop: 2,
  },
  todayEmptyCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xl,
    alignItems: 'center',
  },
  todayEmptyIcon: {
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    marginBottom: SPACING.sm,
  },
  todayEmptyTitle: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
    textAlign: 'center',
  },
  todayEmptyHint: {
    marginTop: SPACING.sm,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
    textAlign: 'center',
  },
  notesCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMuted,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceMutedBorder,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xl,
    gap: SPACING.sm,
    width: '100%',
    minHeight: 194,
  },
  notesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.xs,
    minHeight: 22,
  },
  notesCardFill: {
    flex: 1,
  },
  notesCardStretchWrap: {
    flex: 1,
    alignSelf: 'stretch',
    minHeight: 194,
  },
  notesTitle: {
    color: HOME_SCREEN_STYLE_COLORS.bluePrimary,
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
    textAlign: 'left',
    flex: 1,
  },
  notesInputSurface: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    minHeight: 86,
    justifyContent: 'flex-start',
  },
  notesInput: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.transparent,
    borderRadius: RADIUS.md,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    color: TREASY_DARK_TEXT.secondary,
    minHeight: 76,
    flex: 1,
    textAlignVertical: 'top',
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
  },
  notesInputNudged: {
    transform: [{ translateY: 4 }],
  },
  notesInputFill: {
    flex: 1,
  },
  notesInputFocused: {
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.xs,
    paddingVertical: SPACING.xs,
  },
  notesButton: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.tealPrimary,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.tealBorder,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.lg,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    minHeight: 48,
    ...Platform.select({
      web: { boxShadow: HOME_SCREEN_STYLE_SHADOWS.notesButtonWeb },
      default: {
        shadowColor: HOME_SCREEN_STYLE_COLORS.homeSurfaceDark,
        shadowOpacity: 0.24,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
      },
    }),
  },
  notesButtonNudged: {
    transform: [{ translateY: 8 }],
  },
  notesButtonHover: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.tealBorder,
  },
  notesButtonPressed: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.tealPressed,
  },
  notesButtonDisabled: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.tealDisabled,
    opacity: 1,
    ...Platform.select({
      web: { boxShadow: HOME_SCREEN_STYLE_SHADOWS.none },
      default: { shadowOpacity: 0, elevation: 0 },
    }),
  },
  notesButtonText: {
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  notesNotice: {
    color: HOME_SCREEN_STYLE_COLORS.successSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
    textAlign: 'center',
    minHeight: 16,
  },
  notesNoticeHidden: {
    color: HOME_SCREEN_STYLE_COLORS.transparent,
  },
  cardioCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.cardioNavy,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.cardioBorder,
    padding: SPACING.lg,
    gap: SPACING.sm,
    width: '100%',
  },
  cardioTitle: {
    color: TREASY_DARK_TEXT.primary,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  cardioSubtitle: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  cardioButton: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.cardioButton,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: 'center',
  },
  cardioButtonText: {
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  cardioHint: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
  },
  analysisWrapper: {
    marginTop: 0,
    marginBottom: SPACING.xxl,
  },
  notesToAnalysisDivider: {
    width: '100%',
    height: StyleSheet.hairlineWidth,
    marginTop: SPACING.md,
    marginBottom: SPACING.md,
  },
  analysisCards: {
    gap: SPACING.md,
    backgroundColor: HOME_SCREEN_STYLE_COLORS.sectionNavy,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeBlueDark,
    padding: SPACING.md,
    ...Platform.select({
      web: { boxShadow: HOME_SCREEN_STYLE_SHADOWS.analysisCardsWeb },
      default: {
        shadowColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
        shadowOpacity: 0.35,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 8 },
      },
    }),
  },
  analysisCardsPlain: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.transparent,
    borderWidth: 0,
    borderColor: HOME_SCREEN_STYLE_COLORS.transparent,
    borderRadius: 0,
    padding: 0,
    ...Platform.select({
      web: { boxShadow: HOME_SCREEN_STYLE_SHADOWS.none },
      default: {
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
      },
    }),
  },
  volumeCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: 0,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
  },
  volumeTitle: {
    color: COLORS.blue1,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
    marginBottom: SPACING.sm,
  },
  volumeTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.md,
  },
  volumeLabel: {
    flex: 1,
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
  },
  volumeDeltaChip: {
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  volumeDeltaText: {
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  volumeValue: {
    marginTop: 6,
    color: TREASY_DARK_TEXT.emphasis,
    fontSize: TREASY_TYPE_SCALE.t0.size,
    lineHeight: TREASY_TYPE_SCALE.t0.lineHeight,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  volumeToggleRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    paddingVertical: SPACING.xs,
  },
  volumeToggleText: {
    color: HOME_SCREEN_STYLE_COLORS.linkSoft,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  volumeToggleChevron: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t3.size,
    lineHeight: TREASY_TYPE_SCALE.t3.lineHeight,
    fontWeight: '600',
  },
  volumeListWrapper: {
    marginTop: SPACING.xs,
    borderTopWidth: 1,
    borderTopColor: HOME_SCREEN_STYLE_COLORS.slateDividerDark,
    paddingTop: SPACING.sm,
  },
  volumeListWrapperBorderless: {
    borderTopWidth: 0,
  },
  volumeList: {
    gap: SPACING.xs,
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    paddingVertical: SPACING.xs,
  },
  volumeRowLabel: {
    flex: 1,
    paddingRight: SPACING.md,
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t4.size,
    lineHeight: TREASY_TYPE_SCALE.t4.lineHeight,
    fontWeight: '600',
  },
  volumeRowRight: {
    alignItems: 'flex-end',
  },
  volumeRowChange: {
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  volumeRowValue: {
    marginTop: 2,
    color: TREASY_DARK_TEXT.secondary,
    fontSize: TREASY_TYPE_SCALE.t6.size,
    lineHeight: TREASY_TYPE_SCALE.t6.lineHeight,
    fontWeight: '600',
  },
  volumeEmptyText: {
    color: TREASY_DARK_TEXT.metadata,
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    fontWeight: '400',
    paddingVertical: SPACING.xs,
  },
  analysisCard: {
    backgroundColor: HOME_SCREEN_STYLE_COLORS.surfaceNavy,
    borderRadius: 0,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderColor: HOME_SCREEN_STYLE_COLORS.strokeDark,
    minHeight: 72,
  },
  analysisSectionBorderless: {
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  cardTitle: {
    fontSize: TREASY_TYPE_SCALE.t2.size,
    lineHeight: TREASY_TYPE_SCALE.t2.lineHeight,
    fontWeight: '600',
    color: COLORS.blue1,
    marginBottom: SPACING.xs,
  },
  cardText: {
    fontSize: TREASY_TYPE_SCALE.t5.size,
    lineHeight: TREASY_TYPE_SCALE.t5.lineHeight,
    color: TREASY_DARK_TEXT.metadata,
  },
});

export { styles };

